services:
  3d-print-calc:
    image: ${IMAGE_REPO:-yourdockerhubuser/3d-print-calc}:${IMAGE_TAG:-1.0.0}
    container_name: 3d-print-calc
    environment:
      - TZ=Europe/London
    volumes:
      - /docker/3d-print-calc/data:/data
    ports:
      - 5123:80
    restart: unless-stopped
