services:
  3d-print-calc:
    build: .
    container_name: 3d-print-calc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - C:/docker/3d-print-calc/data:/data
    ports:
      - 5123:80
    restart: unless-stopped
